name: kv-Workflow

on:
  workflow_dispatch:  # Allows manual triggering; also may be use 'workflow_call'
    inputs:  # Define inputs for the workflow
      file:
        description: filename
        required: true
        type: string
      region:
        description: region
        required: true
        type: string
      env:
        description: env
        required: true
        type: string
      subscription:
        description: subscription
        required: true
        type: string
jobs:
  process-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display input values
        run: |
          echo "Processing file: ${{ inputs.file }}"
          echo "Region: ${{ inputs.region }}"
          echo "Environment: ${{ inputs.env }}"
          echo "Subscription: ${{ inputs.subscription }}"
